influxsrv:
  image: tutum/influxdb
  name: influxsrv
  volumes:
    - ./data:/data
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    - PRE_CREATE_DB=cadvisor
cadvisor:
  image: google/cadvisor
  name: cadvisor
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
  ports:
    - "8080:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  links:
    - influxsrv:influxsrv
grafana:
  image: grafana/grafana
  name: grafana
  ports:
    - "3000:3000"
  links:
    - influxsrv:influxsrv
